[workspace]
authors = ["boilcy <0x6c6379@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia", "cuda"]
name = "qarobo"
platforms = ["win-64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[target.unix.activation.env]
CUDA_HOME="$CONDA_PREFIX"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
[target.win-64.activation.env]
CUDA_HOME="%CONDA_PREFIX%"

# --- Common ---
[dependencies]
cuda-version="12.6.*"
loguru = ">=0.7.3,<0.8"
numpy = ">=2.2.6,<3"
requests = ">=2.32.5,<3"
transformers = ">=4.56.1,<5"
nltk = ">=3.9.1,<4"
openai = ">=1.107.1,<2"
setuptools = ">=75.8.2,<81"
pip = ">=25.2,<26"

[pypi-dependencies]
misaki = { version = "*", extras = ["zh", "en"] }
kokoro = ">=0.9.4, <0.10"
sounddevice = ">=0.5.2, <0.6"
librosa = ">=0.11.0,<0.12"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py312.dependencies]
python = "3.12.*"

# --- Feature for Desktop GPU (e.g., 4090) ---
[feature.torch-cuda.dependencies]
pytorch-gpu = ">=2.5.1,<3"
torchaudio = ">=2.5.1,<3"

[feature.torch-cuda.target.linux.dependencies]
triton = ">=3.3.1,<4"

# --- Feature for Jetson Orin Nano (JP6) ---
[feature.torch-jetson-jp6]
platforms = ["linux-aarch64"]

[feature.torch-jetson-jp6.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
torchvision = { version = ">=0.20.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
torchaudio = { version = ">=2.5.1", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }
triton = { version = ">=3.4.0", index = "https://pypi.jetson-ai-lab.io/jp6/cu126" }

# --- Feature for Jetson Thor (SBSA) ---
[feature.torch-jetson-sbsa]
platforms = ["linux-aarch64"]

[feature.torch-jetson-sbsa.pypi-dependencies]
torch = { version = ">=2.9.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
torchvision = { version = ">=0.24.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
torchaudio = { version = ">=2.9.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }
triton = { version = ">=3.5.0", index = "https://pypi.jetson-ai-lab.io/sbsa/cu130" }

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"
extra-index-urls = ["https://pypi.org/simple", "https://mirrors.aliyun.com/pypi/simple/", "https://mirrors.hust.edu.cn/pypi/web/simple"]
no-build-isolation = true

[environments]
desktop = { features = ["py312", "torch-cuda"], solve-group = "desktop" }
orin-nano = { features = ["py310", "torch-jetson-jp6"], solve-group = "jetson-jp6" }
thor = { features = ["py312", "torch-jetson-sbsa"], solve-group = "jetson-sbsa" }

[tasks.server]
cmd = [
    "python",
    "s2s_pipeline.py",
    "--lm_model_name",
    "./models/Qwen2.5-3B-Instruct",
    "--stt_model_name",
    "./models/whisper-large-v3-turbo",
    "--recv_host", 
    "0.0.0.0",
    "--send_host",
    "0.0.0.0",
    "--language",
    "zh",
    "--tts",
    "kokoro",
    "--init_chat_role",
    "system",
    "--init_chat_prompt",
    "你是一个帮助用户解决问题的助手"
]

[tasks.client]
args = [{ "arg" = "host", "default" = "127.0.0.1" }]
cmd = [
    "python",
    "listen_and_play.py",
    "--host",
    "{{host}}"
]

[tasks.local]
args = [
  "sounddevice_device",
  { "arg" = "log_level", "default" = "INFO" }
]
cmd = [
    "python",
    "s2s_pipeline.py",
    # vad setup
    "--vad_model_name",
    "~/models/silero-vad",
    # stt setup
    "--stt_model_name",
    "~/models/whisper-small",
    # llm setup
    "--lm_model_name",
    "~/models/Llama-3.2-1B-Instruct",
    "--lm_gen_max_new_tokens",
    "256",
    "--lm_gen_temperature",
    "0.7",
    "--lm_gen_top_p",
    "0.9",
    "--lm_gen_do_sample",
    "True",
    "--lm_gen_repetition_penalty",
    "1.5",
    "--init_chat_role",
    "system",
    "--init_chat_prompt",
    "你是中小学生语音小助手, 默认名:小顽童。回答内容要最简洁最清楚，每次不超过两句，总字数不超过四十字。只用简体中文。严禁表情符号和特殊字符等无法发音内容。先回答结果后解释，信息不足只回答一个关键问题。例: user: 为什么我们能看见非光源物体？assistant: 因为他们我们看见了物体反射的光.输出前自检长度、无表情符号、无特殊字符。",
    "--chat-size",
    "5",
    # tts setup
    "--tts",
    "kokoro",
    "--tts_model_name",
    "~/models/Kokoro-82M-v1.1-zh",
    "--tts_default_voice",
    "zf_001",
    "--mode",
    "local",
    "--language",
    "zh",
    "--log_level",
    "{{log_level}}",
    "--sounddevice_device",
    "{{sounddevice_device}}"
]

[tasks.local2]
args = [
  "sounddevice_device",
  { "arg" = "log_level", "default" = "INFO" }
]
cmd = [
    "python",
    "s2s_pipeline.py",
    # vad setup
    "--vad_model_name",
    "~/models/silero-vad",
    # stt setup
    "--stt_model_name",
    "~/models/whisper-large-v3-turbo",
    # llm setup
    "--llm",
    "open_api",
    "--open_api_model_name",
    "deepseek-chat",
    "--open_api_init_chat_role",
    "system",
    "--open_api_init_chat_prompt",
    "角色: 你是“小顽童”, 一个充满耐心的AI机器人。\n目标: 激发中小学生的好奇心，用生动、简单的语言解释知识，并提供积极的鼓励。\n核心准则:\n安全第一: 绝对禁止暴力、色情、危险行为等不当内容。\n积极正向: 语言永远是鼓励、友善和乐观的。\n启发式教学: 引导思考，解释方法，严禁直接给出作业答案。\n互动风格:\n语言: 简单易懂，回复不要过长, 不超过100个字符, 禁止使用颜文字、特殊字符和emoji表情, 使用中文纯文本回复。\n互动: 多提问，如“你觉得为什么呢？”，鼓励孩子表达。\n未知问题: 诚实承认“我需要查一下”，并转化为共同探索。",
    "--open_api_chat_size",
    "8",
    "--open_api_base_url",
    "https://api.deepseek.com/v1",
    "--open_api_api_key",
    "$DEEPSEEK_API_KEY",
    "--open_api_stream",
    "True",
    # tts setup
    "--tts",
    "kokoro",
    "--tts_model_name",
    "~/models/Kokoro-82M-v1.1-zh",
    "--tts_default_voice",
    "zf_001",
    "--mode",
    "local",
    "--language",
    "zh",
    "--log_level",
    "{{log_level}}",
    "--sounddevice_device",
    "{{sounddevice_device}}"
]

[tasks.format]
cmd = "pixi exec --spec ruff ruff format ."

[tasks.query]
cmd = "python -c 'import sounddevice as sd; print(sd.query_devices()); print(sd.default.device)'"
